---
output:
  pdf_document: default
  html_document: default
---
```{r config, echo=FALSE, message=FALSE, warning=FALSE, results="hide"}
# Run config first to use dynamic variables in the YAML
if (!require("upstartr")) install.packages("upstartr")
library("upstartr")
run_config()
```

---
title: "`r getOption("startr.title")` -- follows"
author: "`r getOption("startr.author")`"
date: "`r format(Sys.Date(), "%B %d, %Y")`"
output:
  html_document:
    self_contained: false
    code_folding: hide
    toc: true
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
    highlight: textmate
    theme: cosmo
    df_print: kable
---

```{r elt, echo=FALSE, message=FALSE, warning=FALSE, fold_source=TRUE}

source(dir_src("theme.R"))
source(dir_src("palette.R"))
source(dir_src("get.R"))
run_process()
run_analyze()
run_visualize()
```


------------------------------------------------------------------------


### Staffing diversity

```{r p_winnipeg_wps_staffing, echo=FALSE, message=FALSE, warning=FALSE, fig.width=8.66, fig.height=6}
plot(wfp_winnipeg_wps_staffing)
```

```{r dt_winnipeg_wps_staffing, echo=FALSE, message=FALSE, warning=FALSE }

datatable(df_winnipeg_wps_staffing,
  caption = "Table: df_winnipeg_wps_staffing",
  class = "cell-border stripe",
  rownames = FALSE,
  filter = "top",
  options = list(
    pageLength = 10,
    order = list(list(1, "asc"))
  )
)

```


## Six-figure salaries
```{r p_wps_wfps_6figure_salary, echo=FALSE, message=FALSE, warning=FALSE, fig.width=8.66, fig.height=6}
plot(wfp_wps_wfps_6figure_salary)
```

```{r wps_wfps_sixfigure_wide, echo=FALSE, message=FALSE, warning=FALSE }

datatable(wps_wfps_sixfigure_wide,
  caption = "Table: wps_wfps_sixfigure_wide",
  class = "cell-border stripe",
  rownames = FALSE,
  filter = "top",
  options = list(
    pageLength = 10,
    order = list(list(1, "asc"))
  )
)

```
