```{r config, echo=FALSE, message=FALSE, warning=FALSE, results="hide"}
# Run config first to use dynamic variables in the YAML
if (!require("upstartr")) install.packages("upstartr")
library("upstartr")
run_config()
```

---
title: "`r getOption("startr.title")`"
author: "`r getOption("startr.author")`"
date: "`r format(Sys.Date(), "%B %d, %Y")`"
output:
  html_document:
    toc: true
    number_sections: true    
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false    
    highlight: textmate
    theme: cosmo
    df_print: kable
    self_contained: true
    code_folding: hide
---

```{r elt, echo=FALSE, message=FALSE, warning=FALSE, fold_source=TRUE}

source(dir_src("theme.R"))
source(dir_src("palette.R"))
run_process()
run_analyze()
run_visualize()
```


```{r dt_wps_tax_supported_expenses, echo=TRUE, message=TRUE, warning=TRUE }

p_wps_tax_supported_expenses <- ggplot(wps_tax_supported_expenses) + 



datatable(wps_tax_supported_expenses,
  caption = "Table: wps_tax_supported_expenses",
  class = "cell-border stripe",
  rownames = FALSE,
  filter = "top",
  options = list(
    pageLength = 10,
    order = list(list(1, "asc"))
    # language = list(search = 'Filter:'),
    # search = list(regex = TRUE, caseInsensitive = FALSE, search = 'Police')
  )
)
```

